import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Check } from "lucide-react";
import { ConsultationCta } from "@/components/consultation-cta";
import { Container } from "@/components/container";
import { Eyebrow } from "@/components/eyebrow";
import { PageHero } from "@/components/page-hero";

export const metadata: Metadata = { title: "Services", description: "Business transformation consulting, Workday transformation advisory and assurance, executive guidance, and strategic planning for CEOs and executive teams." };

const services = [
  { number:"01", title:"Business Transformation Consulting", lead:"Make transformation coherent, executable, and durable.", copy:"Transformation succeeds when strategy, structure, leadership, and execution move together. Ron helps executive teams identify what must change, align around the choices involved, and build a practical path from intent to implementation.", outcomes:["A clear transformation thesis and shared definition of success","Alignment across leadership, operating priorities, and decision rights","A practical roadmap with accountable owners and meaningful measures","Early identification of friction, dependencies, and adoption risks"] },
  { number:"02", title:"Executive Guidance", lead:"Informed Decision Making when the stakes are high.", copy:"Senior leadership can be isolating, particularly when decisions carry enterprise wide consequences. Ron provides a confidential, objective space to examine the situation, challenge assumptions, and move forward with greater confidence.", outcomes:["Sharper thinking around consequential decisions and tradeoffs","A trusted perspective outside the organization’s internal dynamics","Preparation for critical conversations, transitions, and inflection points","Greater alignment between leadership intent and organizational impact"] },
  { number:"03", title:"Strategic Planning", lead:"Turn direction into a system for progress.", copy:"A strategic plan should guide choices, focus resources, and shape how work gets done. Ron helps leaders create a strategy that is specific enough to act on and resilient enough to adapt as conditions change.", outcomes:["A focused set of strategic priorities grounded in context","Clear choices about what the organization will and will not pursue","Defined ownership, milestones, and decision cadence","A repeatable operating rhythm for reviewing and adapting the plan"] },
  { number:"04", title:"Workday Transformation Advisory & Assurance", lead:"Turn a complex Workday program into an enterprise transformation that delivers.", copy:"Workday programs reshape operating models, processes, data, roles, and the employee experience. Ron provides executive sponsors and program leaders with an independent view of program health, governance, organizational readiness, and the decisions required to move forward with confidence.", outcomes:["A clear view of program health grounded in independent evidence","Stronger executive sponsorship, governance, and decision rights","Early identification of scope, design, data, testing, and readiness risks","A practical roadmap for stabilization, go live readiness, or value realization"], href:"/services/workday-transformation" },
];

export default function ServicesPage(){return <><PageHero eyebrow="Advisory services" title="Move from complexity to focused action." description="Each engagement is shaped around the situation, rather than a fixed methodology, while maintaining a disciplined focus on clarity, alignment, and execution." />
<section className="py-12 sm:py-20"><Container><div className="divide-y divide-navy/15">{services.map((service)=><article key={service.number} className="grid gap-10 py-16 lg:grid-cols-[.18fr_.62fr_1.2fr]"><p className="text-xs font-bold tracking-[.2em] text-gold">{service.number}</p><div><h2 className="font-serif text-4xl leading-[1.06] sm:text-5xl">{service.title}</h2><p className="mt-5 font-serif text-2xl italic text-teal">{service.lead}</p></div><div><p className="text-lg leading-8 text-navy/68">{service.copy}</p><h3 className="mt-8 text-[.68rem] font-bold uppercase tracking-[.2em] text-teal">What the work can create</h3><ul className="mt-5 grid gap-3">{service.outcomes.map((outcome)=><li key={outcome} className="flex gap-3 border-t border-navy/10 pt-3 text-sm leading-6 text-navy/72"><Check className="mt-1 size-4 shrink-0 text-gold" aria-hidden="true" />{outcome}</li>)}</ul>{service.href?<Link href={service.href} className="mt-8 inline-flex items-center gap-2 text-sm font-bold text-teal">Explore Workday advisory <ArrowRight className="size-4" /></Link>:null}</div></article>)}</div></Container></section>
<section className="bg-paper py-24"><Container><div className="grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><Eyebrow>Engagement shape</Eyebrow><h2 className="font-serif text-5xl">Built around the moment.</h2></div><div className="grid gap-px bg-navy/15 sm:grid-cols-3">{[{t:"Focused advisory",c:"Targeted support around a specific decision, transition, or strategic question."},{t:"Leadership partnership",c:"Ongoing counsel for a CEO or executive team navigating sustained complexity."},{t:"Transformation engagement",c:"A structured partnership to align strategy, leadership, and implementation over time."}].map((item)=><article key={item.t} className="bg-paper p-7"><h3 className="font-serif text-3xl">{item.t}</h3><p className="mt-4 leading-7 text-navy/65">{item.c}</p></article>)}</div></div></Container></section><ConsultationCta /></>}
