import type { Metadata } from "next";
import Link from "next/link";
import { ArrowUpRight, CalendarDays, Mail } from "lucide-react";
import { Container } from "@/components/container";
import { Eyebrow } from "@/components/eyebrow";
import { Button } from "@/components/ui/button";
import { siteConfig } from "@/lib/site-config";

export const metadata: Metadata = { title: "Contact", description: "Start a conversation with Ron Jordan about business transformation, executive guidance, or strategic planning." };

export default function ContactPage(){return <section className="min-h-[75vh] py-20 sm:py-28"><Container><div className="grid gap-14 lg:grid-cols-[1.15fr_.85fr] lg:items-start"><div><Eyebrow>Start a conversation</Eyebrow><h1 className="max-w-4xl text-balance font-serif text-6xl leading-[.98] tracking-[-.04em] sm:text-8xl">Bring the question that matters most.</h1><p className="mt-8 max-w-2xl text-xl leading-9 text-navy/68">A first conversation is an opportunity to understand the situation, clarify what you need, and determine whether Ron’s advisory approach is the right fit.</p><div className="mt-12 flex flex-col gap-3 sm:flex-row">{siteConfig.calendlyUrl?<Button asChild size="lg"><Link href={siteConfig.calendlyUrl} target="_blank" rel="noreferrer"><CalendarDays className="size-4" /> Choose a time <ArrowUpRight className="size-4" /></Link></Button>:<Button size="lg" disabled><CalendarDays className="size-4" /> Scheduling link coming soon</Button>}{siteConfig.contactEmail?<Button asChild size="lg" variant="outline"><Link href={`mailto:${siteConfig.contactEmail}`}><Mail className="size-4" /> {siteConfig.contactEmail}</Link></Button>:<Button size="lg" variant="outline" disabled><Mail className="size-4" /> Contact email to be added</Button>}</div></div><aside className="border-t border-navy/20 pt-8 lg:mt-10"><p className="text-[.68rem] font-bold uppercase tracking-[.2em] text-teal">A useful place to begin</p><ol className="mt-6 divide-y divide-navy/12 border-y border-navy/12">{["What is changing or needs to change?","Why does this matter now?","What would meaningful progress look like?"].map((question,index)=><li key={question} className="flex gap-6 py-6"><span className="text-xs font-bold text-gold">0{index+1}</span><span className="font-serif text-2xl leading-tight">{question}</span></li>)}</ol><p className="mt-7 text-sm leading-6 text-navy/55">Conversations are confidential. Choose a convenient time through Calendly to begin.</p></aside></div></Container></section>}
