import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { ConsultationCta } from "@/components/consultation-cta";
import { Container } from "@/components/container";
import { Eyebrow } from "@/components/eyebrow";
import { PageHero } from "@/components/page-hero";
import { PortraitPlaceholder } from "@/components/portrait-placeholder";
import { Button } from "@/components/ui/button";

export const metadata: Metadata = { title: "About Ronald L. Jordan Jr.", description: "Learn about Ronald L. Jordan Jr., Founder and Chief Executive & Strategy Officer of Aurelian Advisory Group." };

export default function AboutPage() {
  return <>
    <PageHero eyebrow="About Ron" title="A steady perspective for consequential moments." description="Ron works alongside executive leaders when the stakes are high, the variables are complex, and forward movement requires more than another framework." />
    <section className="py-24 sm:py-32"><Container><div className="grid gap-14 lg:grid-cols-[.82fr_1.18fr] lg:items-start"><PortraitPlaceholder compact /><div className="lg:pl-10"><Eyebrow>Point of view</Eyebrow><h2 className="text-balance font-serif text-5xl leading-[1.04] tracking-[-.03em] sm:text-6xl">Transformation becomes possible when transparency, courage, and execution meet.</h2><div className="mt-10 space-y-6 text-lg leading-8 text-navy/68"><p>Transformation is rarely held back by a lack of ideas. More often, progress slows when priorities compete, decisions remain unresolved, or leaders lack a candid space to examine what is really happening.</p><p>Ron’s role is to ensure leaders see the whole picture, test assumptions, make strategic decisions, and establish the roadmap for sustained action. The work is thoughtful and direct, always grounded in the realities of the organization and the people responsible for moving it forward.</p><p className="border-l-2 border-gold pl-6 font-serif text-2xl leading-9 text-navy">The goal is not advice for its own sake. It is stronger leadership, sharper alignment, and solutions that resolve challenges.</p></div></div></div></Container></section>
    <section className="border-y border-navy/10 bg-paper py-24"><Container><div className="grid gap-12 lg:grid-cols-[.65fr_1.35fr]"><Eyebrow>Working principles</Eyebrow><div className="grid gap-8 sm:grid-cols-2">{[{t:"Clarity before activity",c:"Define the real question and the outcome that matters before adding motion."},{t:"Candor with care",c:"Make room for the honest conversations that sharpen decisions and strengthen trust."},{t:"Context over formulas",c:"Use sound principles without forcing complex organizations into a generic playbook."},{t:"Progress through ownership",c:"Create explicit decisions, accountable owners, and operating rhythms that sustain action."}].map((item)=><article key={item.t} className="border-t border-navy/20 pt-6"><h3 className="font-serif text-3xl">{item.t}</h3><p className="mt-4 leading-7 text-navy/65">{item.c}</p></article>)}</div></div></Container></section>
    <section className="py-24 sm:py-32"><Container><div className="grid gap-12 lg:grid-cols-[.65fr_1.35fr]"><div><Eyebrow>Professional background</Eyebrow><h2 className="text-balance font-serif text-5xl leading-[1.05] sm:text-6xl">Experience that earns trust.</h2><div className="mt-8 border-l-2 border-gold pl-5"><p className="font-serif text-2xl text-navy">Ronald L. Jordan Jr.</p><p className="mt-2 text-sm font-semibold leading-6 text-teal">Founder &amp; Chief Executive &amp; Strategy Officer<br />Aurelian Advisory Group</p></div></div><div><div className="space-y-6 text-lg leading-8 text-navy/68"><p>Ronald L. Jordan Jr. is the Founder and Chief Executive &amp; Strategy Officer of Aurelian Advisory Group, an independent business transformation assurance and executive advisory firm he built to close a structural gap in how organizations govern high-stakes enterprise transformations.</p><p>Ron founded Aurelian on a conviction formed over nearly twenty years inside the world&rsquo;s largest transformation programs: the people closest to a transformation are the least equipped to grade it honestly, and no other investment of comparable size operates without an independent check on whether it&rsquo;s working. He set out to build the firm that provides that check. Aurelian is structurally independent, senior-led, and organized around a proprietary diagnostic method, the Transformation Assurance Index&trade;, which he created to make an honest read repeatable rather than a matter of individual judgment.</p><p>Before founding Aurelian, Ron spent a decade across Ernst &amp; Young, Accenture, and Deloitte leading and rescuing medium- to large-scale business transformation, Enterprise Resource Planning, and Workday transformation programs. He leads Aurelian&rsquo;s strategy, governance, and growth, and works directly with CHROs, CIOs, CFOs, CEOs, boards, and program sponsors staking their organization&rsquo;s next decade on a transformation program&rsquo;s success.</p><p>Ron serves as Board Chair of JBN | JORDANCO, a local philanthropic organization, volunteers with Junior Achievement, and is a member of United Way&rsquo;s African American Partnership. Ron is also a Founder of Magnitudo, an Executive Coaching and Career Acceleration Program that provides Proven Strategies for Professionals with Unfulfilled Potential.</p></div><Button asChild variant="outline" className="mt-9"><Link href="/contact">Start a conversation <ArrowRight className="size-4" /></Link></Button></div></div></Container></section>
    <ConsultationCta />
  </>;
}
